procesy_a:
	gcc src/procesy_a.c -o build/procesy_a
procesy_b:
	gcc src/procesy_b.c -o build/procesy_b
procesy_c:
	gcc src/procesy_c.c -o build/procesy_c
procesy_d:
	gcc src/procesy_d.c -o build/procesy_d
procesy_e:
	gcc src/procesy_e.c -o build/procesy_e
procesy_f:
	gcc src/procesy_f.c -o build/procesy_f
