sig_a:
	gcc "src/sig_a.c" -Wall -pedantic -std=c99 -o "build/sig_a"
sig_b:
	gcc "src/sig_a.c" -Wall -pedantic -std=c99 -o "build/sig_a"
	gcc "src/sig_b.c" -Wall -pedantic -std=c99 -o "build/sig_b"
sig_c:
	gcc "src/sig_a.c" -Wall -pedantic -std=c99 -o "build/sig_a"
	gcc "src/sig_c.c" -Wall -pedantic -std=c99 -o "build/sig_c"

